name: Deploy go.opentelemetry.io

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
        project_id: ${{ secrets.GOOGLE_PROJECT }}
    - run: |
        gcloud --quiet config set project ${{ secrets.GOOGLE_PROJECT }}
        gcloud --quiet config set compute/zone ${{ secrets.GOOGLE_COMPUTE_ZONE }}
    - run: |
        cd go.opentelemetry.io
        chmod 755 deploy.sh
        ./deploy.sh 